"""final 

Revision ID: 33a3edf428c1
Revises: e4db0cd34e2d
Create Date: 2024-01-11 07:13:42.206036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a3edf428c1'
down_revision = 'e4db0cd34e2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
