"""

Revision ID: e4db0cd34e2d
Revises: 7169aa60d8ea
Create Date: 2024-01-11 07:08:07.567294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4db0cd34e2d'
down_revision = '7169aa60d8ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
